apiVersion: apps/v1
kind: Deployment
metadata:
  name: snyk-deployment
  labels:
    app.kubernetes.io/name: snyk-deployment
    helm.sh/chart: snyk-deployment-0.1.0
    app.kubernetes.io/instance: snyk-deployment
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: snyk-deployment
      app.kubernetes.io/instance: snyk-deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: snyk-deployment
        app.kubernetes.io/instance: snyk-deployment
    spec:
      hostPID: true
      containers